export type MachineryItem = {
  no: string
  name: string
  make: string
  quantity: number | string
  isCategory?: boolean
}

export const machinery: MachineryItem[] = [
  { no: '01', name: 'EXCAVATOR', make: '', quantity: '', isCategory: true },
  { no: '01.1', name: 'JCB - 3D', make: 'JCB INDIA LTD', quantity: 3 },
  { no: '01.2', name: 'JCB - 3 DX', make: 'JCB INDIA LTD', quantity: 2 },
  { no: '01.3', name: 'TEREX TLB 844S, VECTRA', make: 'TEREX VECTRA', quantity: 2 },
  { no: '01.4', name: 'POKLAIN - JS-80', make: 'JCB INDIA LTD', quantity: 2 },
  { no: '01.5', name: 'POKLAIN - JS-130', make: 'JCB INDIA LTD', quantity: 1 },
  { no: '01.6', name: 'POKLAIN - L & T 190', make: 'L&T', quantity: 2 },
  { no: '02', name: 'TRACTOR LOADER', make: 'MAHINDRA', quantity: 5 },
  { no: '03', name: 'BULL DOZER', make: 'HINDUSTAN', quantity: 3 },
  { no: '04', name: 'PAVER MACHINE', make: 'APOLLO', quantity: 1 },
  { no: '05', name: 'ROAD ROLLER MACHINE', make: '', quantity: '', isCategory: true },
  { no: '05.1', name: 'Vibro Roller - Compactor 11.5 Mt. - 35 Mt Compaction Capacity.', make: 'L&T CASE', quantity: 1 },
  { no: '05.2', name: 'Vibro Roller - Compactor 1mt. - 3 Mt Compaction Capacity.', make: 'L&T', quantity: 2 },
  { no: '05.3', name: 'STATIC ROLLER - 10 MT', make: 'ACCEL INFRATECH', quantity: 3 },
  { no: '06', name: 'PLATE COMPACTOR', make: '', quantity: '', isCategory: true },
  { no: '06.1', name: 'ELECTRIC', make: 'KIRLOSKAR', quantity: 8 },
  { no: '06.2', name: 'DIESEL', make: 'KIRLOSKAR', quantity: 10 },
  { no: '07', name: 'TRACTOR', make: 'MAHINDRA / SWARAJ', quantity: 15 },
  { no: '08', name: 'DUMPER', make: 'TATA', quantity: 10 },
  { no: '09', name: 'WATER TANKER - 12000 LTR', make: 'TATA', quantity: 5 },
  { no: '10', name: 'WATER TANKER - 4000 LTR', make: 'MAHINDRA', quantity: 6 },
  { no: '11', name: 'WATER STORAGE TANK', make: '', quantity: '', isCategory: true },
  { no: '11.1', name: '2000 LTR', make: 'SYNTEX', quantity: 20 },
  { no: '11.2', name: '1500 LTR', make: 'SYNTEX', quantity: 20 },
  { no: '11.3', name: '1000 LTR', make: 'SYNTEX', quantity: 30 },
  { no: '12', name: 'SELF LOADING CONCRETE MIXER - 2 CUM', make: 'AJAX', quantity: 3 },
  { no: '13', name: 'SELF LOADING CONCRETE MIXER - 4 CUM', make: 'AJAX', quantity: 2 },
  { no: '14', name: 'RMC - 800 BATCHING PLANT', make: 'UNIVERSAL', quantity: 2 },
  { no: '15', name: 'RMC - BATCHING PLANT', make: '1050-UNIVERSAL', quantity: 1 },
  { no: '16', name: 'BATCHING PLANT - 18 CUM, RM 18 DX', make: 'UNIVERSAL', quantity: 2 },
  { no: '17', name: 'BATCHING PLANT - 30 CUM', make: 'GAYATRI', quantity: 1 },
  { no: '18', name: 'BATCHING PLANT - 25 CUM', make: 'VINUS', quantity: 1 },
  { no: '19', name: 'BATCHING PLANT - 18 CUM', make: 'SCHWING', quantity: 1 },
  { no: '20', name: 'TRANSIT MIXER 6 CUM', make: 'GREAVES', quantity: 2 },
  { no: '21', name: 'TRANSIT MIXER 6 CUM', make: 'AQUARIOUS', quantity: 4 },
  { no: '22', name: 'CONCRETE PUMP - 703-D', make: 'UNIVERSAL', quantity: 6 },
  { no: '23', name: 'CONCRETE PUMP - SP1200', make: 'SCHWING', quantity: 1 },
  { no: '24', name: 'TOUGH RIDER', make: 'SHREE RAM / SAFARI', quantity: 8 },
  { no: '25', name: 'MIXER MACHINE', make: 'SHREE RAM / SAFARI', quantity: 8 },
  { no: '26', name: 'WEIGHBATCHER', make: 'MEGACON CONSTRUCTION', quantity: 10 },
  { no: '27', name: 'DMC PILE - TRUCK MOUNTED MACHINE', make: 'ACE', quantity: 2 },
  { no: '28', name: 'ACE MTC TOWER CRANE - 3625', make: 'ACE', quantity: 1 },
  { no: '29', name: 'CRANE - 35 MT LIFTING CAPACITY', make: 'ACE', quantity: 3 },
  { no: '30', name: 'HYDRA', make: 'ESCORT', quantity: 3 },
  { no: '31', name: 'HYDRA - F-15', make: 'ACE', quantity: 1 },
  { no: '32', name: 'LIFT MACHINE', make: 'SAFAR', quantity: 3 },
  { no: '33', name: 'WINCH', make: 'ININGBO M/C. CHINA', quantity: 1 },
  { no: '34', name: 'VP 4-30 PAVER / CONCRETE BLOCK MAKING MACHINE', make: 'KIRLOSKAR', quantity: 12 },
  { no: '35', name: 'ELECTRIC VIBRATOR WITH NEEDLE', make: 'ENFIELD', quantity: 10 },
  { no: '36', name: 'PETROL VIBRATOR', make: 'WALKER', quantity: 5 },
  { no: '37', name: 'ELECTRICAL VIBRATOR', make: 'KIRLOSKAR', quantity: 3 },
  { no: '38', name: 'DE-WATERING ELECTRIC MOTOR - 5 HP', make: 'KIRLOSKAR', quantity: 8 },
  { no: '39', name: 'DE-WATERING ELECTRIC MOTOR - 1 HP', make: 'MARSHAL', quantity: 3 },
  { no: '40', name: 'DE-WATERING DIESEL PUMP - 5 HP', make: 'MARSHAL', quantity: 2 },
  { no: '41', name: 'DE-WATERING DIESEL MUD PUMP - 10 HP', make: 'HILTI', quantity: 5 },
  { no: '42', name: 'GRINDER MACHINE - BIG', make: 'HILTI', quantity: 5 },
  { no: '43', name: 'GRINDER MACHINE - SMALL', make: 'HILTI', quantity: 5 },
  { no: '44', name: 'DRILLING MACHINE', make: 'HILTI', quantity: 4 },
  { no: '45', name: 'BREAKER MACHINE', make: 'HILTI', quantity: 3 },
  { no: '46', name: 'REBARRING MACHINE', make: 'SUBANDHU', quantity: 15 },
  { no: '47', name: 'WELDING MACHINE', make: 'OM ENTERPRISE', quantity: 6 },
  { no: '48', name: 'STEEL CUTTING MACHINE - HYDRAULIC', make: 'DYNEMIX INDIA', quantity: 12 },
  { no: '49', name: 'STEEL CUTTING MACHINE - MANUAL', make: 'OM ENTERPRISE', quantity: 6 },
  { no: '50', name: 'STEEL BENDING MACHINE - HYDRAULIC', make: 'DYNEMIX INDIA', quantity: 10 },
  { no: '51', name: 'PLY CUTTER MACHINE', make: 'BOSCH', quantity: '', isCategory: true },
  { no: '51.1', name: 'CHAIN KUPPY', make: 'BOSCH', quantity: 1 },
  { no: '51.2', name: 'CHAIN KUPPY - 10 MT', make: 'BOSCH', quantity: 2 },
  { no: '51.3', name: 'CHAIN KUPPY - 5 MT', make: 'BOSCH', quantity: 3 },
  { no: '51.4', name: 'CHAIN KUPPY - 3 MT', make: 'BOSCH', quantity: 8 },
  { no: '52', name: 'PUG MACHINE', make: 'GODREJ', quantity: 2 },
  { no: '53', name: 'FLOOR SCRUBBER', make: 'MAHINDRA', quantity: 2 },
  { no: '54', name: 'AMBULANCE', make: 'TATA', quantity: '3 SET' },
  { no: '55', name: 'DIESEL GENERATOR', make: '', quantity: '', isCategory: true },
  { no: '55.1', name: 'DG - 125 KVA', make: 'MAHINDRA', quantity: 1 },
  { no: '55.2', name: 'DG - 62.5 KVA', make: 'MAHINDRA', quantity: 3 },
  { no: '55.3', name: 'DG - 35 KVA', make: 'MAHINDRA', quantity: 1 },
  { no: '55.4', name: 'DG - 25 KVA', make: 'MAHINDRA', quantity: 3 },
  { no: '55.5', name: 'DG - 20 KVA', make: 'KIRLOSKAR', quantity: 1 },
  { no: '55.6', name: 'DG - 7.5 KVA', make: 'KIRLOSKAR', quantity: 5 },
  { no: '56', name: 'PORTA CABINS - OFFICE', make: 'SATYAM PREFAB / ICON', quantity: 10 },
  { no: '57', name: 'CEMENT STORAGE CONTAINER - 40 X 8 FT', make: 'ENDEAVOUR', quantity: 2 },
  { no: '58', name: 'WEIGHBRIDGE - 50 TONS', make: 'TEREX', quantity: 4 },
  { no: '59', name: 'SELF POWERED MOVABLE FLOOD LIGHT', make: 'PANASONIC', quantity: 1 },
  { no: '60', name: 'BOOM PUMP', make: 'SCHWING', quantity: 1 },
  { no: '61', name: 'BOOM PUMP', make: 'SANY', quantity: 1 },
  { no: '62', name: 'MOBILE TOWER CRANE', make: 'ALFA', quantity: 1 },
  { no: '63', name: 'MOBILE TOWER CRANE', make: 'ACE', quantity: 3 },
  { no: '64', name: 'TEMPO', make: 'FORCE MOTOR', quantity: 4 },
  { no: '65', name: 'PICKUP', make: 'TATA', quantity: 1 },
  { no: '66', name: 'TRAILER', make: 'EICHER', quantity: 1 },
  { no: '67', name: 'EICHER TEMPO', make: 'EICHER', quantity: 1 },
  { no: '68', name: 'TRAX TOOFAN Bs6', make: 'TOOFAN FORCE', quantity: 1 },
  { no: '69', name: 'TRAX TOOFAN', make: 'TOOFAN FORCE', quantity: 3 },
  { no: '70', name: 'BOLERO', make: 'BOLERO', quantity: 1 },
  { no: '71', name: 'ECO', make: 'ECCO 7 STAR', quantity: 1 },
  { no: '72', name: 'THEODOLITE', make: 'SOKKIA', quantity: 2 },
  { no: '73', name: 'AUTO LEVEL', make: 'SOKKIA / PENTAX', quantity: 2 },
  { no: '74', name: 'LAB EQUIPMENT', make: 'SHREEJI INSTRUMENTS / OM ENTERPRISE', quantity: 10 },
]
