import type { Metadata } from 'next'
import { Inter, Hanken_Grotesk } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import { SmoothCursor } from '@/components/motion/SmoothCursor'
import { LenisProvider } from '@/components/motion/LenisProvider'
import { PageTransitionOverlay } from '@/components/motion/PageTransitionOverlay'
import { PageWrapper } from '@/components/motion/PageWrapper'
import { ScrollProgress } from '@/components/motion/ScrollProgress'
import { Toaster } from 'sonner'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const hanken = Hanken_Grotesk({
  subsets: ['latin'],
  variable: '--font-hanken',
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL('https://bdbuildcon.com'),
  title: 'BD Buildcon LLP | Industrial EPC Contractor, Bharuch, Gujarat',
  description:
    'Turnkey industrial EPC contractor since 1995. All projects completed on deadline with zero accidents. ISO 9001:2015 certified · CRISIL SME 3 rated · ₹200+ Cr delivered.',
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://bdbuildcon.com',
    siteName: 'BD Buildcon LLP',
    title: 'BD Buildcon LLP | Industrial EPC Contractor',
    description:
      'Turnkey industrial EPC contractor since 1995. All projects completed on deadline with zero accidents.',
    // Share image is generated by app/opengraph-image.tsx (branded card).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BD Buildcon LLP | Industrial EPC Contractor',
    description:
      'Turnkey industrial EPC contractor since 1995. All projects completed on deadline with zero accidents.',
    // Falls back to the opengraph-image card.
  },
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${hanken.variable}`}>
      <body className="font-body text-ink bg-white antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'ConstructionCompany',
              name: 'BD Buildcon LLP',
              url: 'https://bdbuildcon.com',
              logo: 'https://bdbuildcon.com/logo.svg',
              description: 'Turnkey industrial EPC contractor since 1995.',
              address: {
                '@type': 'PostalAddress',
                streetAddress: 'Millenium Arcade, Opp SVM Engineering College, Old National Highway 8',
                addressLocality: 'Bharuch',
                addressRegion: 'Gujarat',
                postalCode: '392002',
                addressCountry: 'IN',
              },
              contactPoint: {
                '@type': 'ContactPoint',
                telephone: '+919879100355',
                contactType: 'customer service',
              },
            }),
          }}
        />
        <LenisProvider>
          <SmoothCursor />
          <ScrollProgress />
          <PageTransitionOverlay />
          <Header />
          <PageWrapper>
            <main>{children}</main>
          </PageWrapper>
          <Footer />
          <Toaster position="bottom-right" richColors />
        </LenisProvider>
      </body>
    </html>
  )
}
